#!/bin/sh

# ____                              
#| __ ) ___ _ ____      ___ __ ___  
#|  _ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|____/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_| 
#

#### MONITOR SETUP ####
if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
  xrandr --output HDMI-1-0 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1-0
fi
brightnessctl s 80%
#######################

#### INPUT CONFIG ####
xinput set-prop ELAN1203:00\ 04F3:307A\ Touchpad libinput\ Tapping\ Enabled 1
xinput set-prop ELAN1203:00\ 04F3:307A\ Touchpad libinput\ Natural\ Scrolling\ Enabled 1    	  
#######################

#### CURSOR CONFIG ####
xsetroot -cursor_name left_ptr
#######################

#### BSPWM CONFIG ####
bspc config border_width		              0
bspc config window_gap                    15
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true

bspc rule -a discord desktop='^7' follow=off
bspc rule -a spotify desktop='^8' follow=off
bspc rule -a zathura state=tiled
#######################

#### WORKSPACE CONFIG ####
if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
  bspc monitor HDMI-1-0 -d 1 2 3 4
  bspc monitor eDP-1 -d 5 6 7 8
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
fi
#######################

#### ENV ####
export CORE_TEMP_HWMON_PATH=$(find /sys/devices/platform/coretemp.0/hwmon -name temp1_input)
export TEST=3
#######################

#### AUTOSTART APPS ####
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
setxkbmap -layout it
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#######################

#### APPLETS ####
dunst &
blueman-applet &
nm-applet &
pgrep -x pasystray > /dev/null || pasystray &
#######################

#### POLYBAR ####
$HOME/.config/polybar/launch-bars.sh
#######################
